---
title: "2026/02/23"
date: 2026-02-23
tags: [weekly]
meeting: [Hugo Ledoux]
---

## Results since previous meeting

- First results of roofprints obtained by matching lines parallel to the edges in BD TOPO to points detected as potential roof edges in 2D (projected vertically)

## Material for discussion

- To avoid matching with a wrong neighbor building, it could be useful to use the distance from the initial edge to the potential better edge as an indication.
  A slightly less performant but closer edge can be a better choice.
  Another idea can be to see how the different edges for a building can be connected.

## Discussion

- Regularization could be useful to ensure 90 degree angles when it is likely.
  However it could also result in edges that are less aligned to the read edges, so the 90° constraint should preferably be used on combination with matching with the point cloud.

## Work until next meeting

- Roofprints:
  - [x] Try to match points in 3D
  - [ ] Look into the potential of using the distance to the current outline as an indication as well
  - [ ] Try to extract the length of the matched edges as well instead of simply finding infinite lines
  - [ ] Try regularization on the buildings (see [this CGAL package](https://doc.cgal.org/latest/Shape_regularization/index.html) or [this paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=CLbvVRQAAAAJ&citation_for_view=CLbvVRQAAAAJ:Y0pCki6q_DkC) by [this researcher](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=7XqwgZoAAAAJ&citation_for_view=7XqwgZoAAAAJ:_Qo2XoVZTnwC)):
- Pipeline:
  - [x] Make a script to download tiles automatically. Tiles index is available [on Zenodo](https://zenodo.org/records/13793544), and there is a [script there](https://github.com/cusicand/lidarhd_ign_downloader)
  - [x] Make a script to extract and merge LiDAR flight axes
  - [ ] Integrate the script to compute the scanning vehicle trajectory
  - [x] Make a script to merge point clouds
